version: '3'
services:
  server:
    container_name: prestalo-server
    build:
       context: .
       dockerfile: ./Dockerfile
    ports:
      - '5000:5000'
    env_file:
      - ./server/.env
  mongodb:
    image: mongo
    container_name: prestalo-mongo-db
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
volumes:
  mongodb_data: