import type {Metadata} from "next";
import React from "react";
import {MantineProvider} from "@mantine/core";
import "@mantine/core/styles.css";

export const metadata: Metadata = {
    title: "Prestalo Technical Test",
    description: "Generated by create next app",
};

export default function RootLayout(
    {children,}: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <html lang="en">
        <body>
        <MantineProvider>
            {children}
        </MantineProvider>
        </body>
        </html>
    );
}
